Document: cclient
Title: Debian cclient Manual
Author: <insert document author here>
Abstract: This manual describes what cclient is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/cclient/cclient.sgml.gz

Format: postscript
Files: /usr/share/doc/cclient/cclient.ps.gz

Format: text
Files: /usr/share/doc/cclient/cclient.text.gz

Format: HTML
Index: /usr/share/doc/cclient/html/index.html
Files: /usr/share/doc/cclient/html/*.html


